server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包(告诉mybaties扫描这个包下面的实体类）
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件（DeptMapper.xml 完成 DeptDaoImpl 的工作）
    
spring:
   application:
    name: microservicecloud-dept                            #对外暴露的微服务名字，这个名字很重要，Eureka中会用到
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.198.136:3306/clouddb01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka   #需要入住的eureka地址（即 eureka-7001 的 defaultZone）

