server:
  port: 80

#客户端中开启熔断
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false   #Eureka自己不注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/